### ISSUE TITLE
Add Confirming Token Page

### ISSUE THREAD

**Issue by OverlordsIII** [Elephant-Learning/Elephant-Website#11]
Add a confirming token page that takes a token parameter (maybe something like `elephantsuite.me/confirm?token=[token]`) and will then send a confirm token request to the backend confirming that token and then sending the user back to the home page.

Is related to [Backend #38](https://github.com/Elephant-Learning/Elephant-Rearend/issues/38)

**Comment by ronakkothari123** [comment]
Should be finished, but awaiting checks (backend email).

**Comment by ronakkothari123** [comment]
Finished and closing
