### ISSUE TITLE
Add HTML/CSS For Confirmation Email

### ISSUE THREAD

**Issue by OverlordsIII** [Elephant-Learning/Elephant-Website#12]
Add HTML and CSS for sending a confirmation email. Also add a section within the code that can be replaced with the actual link within code (maybe have `href=elephantsuite.me/confirm?token=[token]`) and then the backend would replace `[token]` with the actual users token within code.

Related to [Backend #38](https://github.com/Elephant-Learning/Elephant-Rearend/issues/38)

**Comment by ronakkothari123** [comment]
HTML/CSS should be created. Will close when checks are made.

**Comment by OverlordsIII** [comment]
Currently is breaking when in email or mail apps compared to normal browswer

**Comment by OverlordsIII** [comment]
Managed some workaround but still not completely working, so will leave open

**Comment by ronakkothari123** [comment]
Bruh I actually forgot to take pictures of images. Give me a quick second

**Comment by ronakkothari123** [comment]
Sent you on Discord @OverlordsIII

**Comment by ronakkothari123** [comment]
Marking closed because I think it's done.
