### ISSUE TITLE
Flashcards Carousel Buttons Not Working

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Website#14]
When hovering exactly over the image, it doesn't want to cooperate. Am crying now, and will fix once I calm down.

**Comment by ronakkothari123** [comment]
Tears stop but I'm still shaking... Give me a moment

**Comment by OverlordsIII** [comment]
We hold a moment of silence for our lost brother Ronak Kothari.

**Comment by ronakkothari123** [comment]
Unfortunately, just when I thought I was back to normal, I started spouting tears again. Just wish it could work again.

**Comment by OverlordsIII** [comment]
We're here for you. Know you have support during these troubling times

**Comment by ronakkothari123** [comment]
Thank you so much! Knowing you're here with me, I'll probably get through this!

**Comment by OverlordsIII** [comment]
That's the spirit. You can do this Ronak J Kothari!

**Comment by ronakkothari123** [comment]
Stopped Crying and I fixed.
