### ISSUE TITLE
Issue with responsivity

### ISSUE THREAD

**Issue by OverlordsIII** [Elephant-Learning/Elephant-Website#3]
Elephant becomes deranged when using it on mobile
![image](https://user-images.githubusercontent.com/69648849/170845500-a5606e87-a951-4c0b-a040-796b7f259969.png)

1. Visit elephantsuite.me on a mobile device

I think a way this could be fixed would be stacking all the elements top to bottom instead of side to side, maximizing storage

 - Device: iPhone SE
 - OS: iOS 15.4.1
 - Browser: safari

**Comment by nealtheseal108** [comment]
Yeah, I'm working on that in the new landing page. That will be fixed.

**Comment by OverlordsIII** [comment]
PTP coming in clutch as usual

**Comment by ronakkothari123** [comment]
Marking Closed as mobile development will be separate.
