### ISSUE TITLE
Add Ability to Backpack Cards

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Website#7]
So far work to place backpacked cards in the editor is finished, however the ability to backpack cards isn't. I will post updates here.

**Comment by ronakkothari123** [comment]
Backend should be complete, however adding @OverlordsIII in case of errors.

**Comment by OverlordsIII** [comment]
Ye the backend for backpacks is finished

**Comment by ronakkothari123** [comment]
@OverlordsIII removing Enhancement and labeling as Bug as there are a few errors that come with backpacking a card.

**Comment by ronakkothari123** [comment]
Issue Fixed... closing
